// Load Success
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
export const LOAD_DATA_FAILURE = 'LOAD_DATA_FAILURE';
export const LOAD_IMAGE_SUCCESS = 'LOAD_IMAGE_SUCCESS';
export const LOAD_IMAGE_FAILURE = 'LOAD_IMAGE_FAILURE';
export const LOAD_DETAIL_SUCCESS = 'LOAD_DETAIL_SUCCESS';
export const LOAD_DETAIL_FAILURE = 'LOAD_DETAIL_FAILURE';
export const LOAD_RECOMMENDATION_SUCCESS = 'LOAD_RECOMMENDATION_SUCCESS';
export const LOAD_RECOMMENDATION_FAILURE = 'LOAD_RECOMMENDATION_FAILURE';
export const EDIT_ON = 'EDIT_ON';
export const EDIT_OFF = 'EDIT_OFF';
export const MOVIE_SELECTED = 'MOVIE_SELECTED';
export const MOVIE_DESELECTED = 'MOVIE_DESELECTED';
